protected/models/Role.php
<?php

/**
 * This is the model class for table "role".
 *
 * The followings are the available columns in table 'role':
 * @property integer $id
 * @property string $nama
 *
 * The followings are the available model relations:
 * @property User[] $users
 */
class Role extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Role the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'role';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nama', 'required'),
			array('nama', 'length', 'max'=>255),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nama', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'users' => array(self::HAS_MANY, 'User', 'role_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nama' => 'Nama',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nama',$this->nama,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/RoleController.php
<?php

class RoleController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/constellation/index';

/**
* @return array action filters
*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'accessRole'
		);
	}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('index','view'),
'users'=>array('*'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('create','update','access'),
'users'=>array('@'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete'),
'users'=>array('@'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}
	public function actionAccess($id)
	{
		if(!empty($_POST['RoleAccess']))
		{
			foreach(RoleAccess::model()->findAllByAttributes(array('role_id'=>$id)) as $data)
			{
				$data->status = 0;
				$data->save();
			}	
			
			foreach($_POST['RoleAccess'] as $key => $value)
			{
				if($value==1)
				{
					$roleAccess = RoleAccess::model()->findByAttributes(array('access_id'=>$key,'role_id'=>$id));
					
					if($roleAccess === null)
					{
						$roleAccess = new RoleAccess;
						$roleAccess->access_id = $key;
						$roleAccess->role_id = $id;
					}
					
					$roleAccess->status = 1;
					
					$roleAccess->save();
				}
			}
			
			Yii::app()->user->setFlash('success','Data berhasil disimpan');
		}
		
		$this->render('access',array(
			'model'=>$this->loadModel($id),
		));
	}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
	public function actionCreate()
	{
		$model=new Role;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Role']))
		{
			$model->attributes=$_POST['Role'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('admin'));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Role']))
		{
			$model->attributes=$_POST['Role'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('admin'));
			}
		}
		
		Yii::app()->user->setFlash('info','Silahkan update data');
		
		$this->render('update',array(
			'model'=>$model,
		));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Role');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
	public function actionAdmin()
	{
		$role=new Role('search');
		$role->unsetAttributes();  // clear any default values
		if(isset($_GET['Role']))
			$role->attributes=$_GET['Role'];

		$this->render('admin',array(
			'role'=>$role,
		));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Role::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='role-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/role/_admin.php
<?php $this->widget('booster.widgets.TbGridView',array(
		'id'=>'role-grid',
		'type'=>'striped bordered',
		'dataProvider'=>$role->search(),
		'filter'=>$role,
		'columns'=>array(
			array(
				'header'=>'Akses',
				'type'=>'raw',
				'value'=>'CHtml::link("<i class=\"glyphicon glyphicon-lock\"></i>",array("role/access","id"=>$data->id))',
				'htmlOptions' => array('style' => 'text-align:center;width:5%;'),
			),
			'nama',
			array(
				'class'=>'booster.widgets.TbButtonColumn',
				'template'=>'{update} {delete}',
			),
		),
)); ?>

protected/views/role/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'role-form',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'nama',array('class'=>'span5','maxlength'=>255)); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok white',
			'label'=>'Simpan',
			'htmlOptions'=>array('class'=>'big-button'),
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/role/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'nama',array('class'=>'span5','maxlength'=>255)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/role/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nama')); ?>:</b>
	<?php echo CHtml::encode($data->nama); ?>
	<br />


</div>

protected/views/role/access.php
<?php
$this->breadcrumbs=array(
	'Data Role'=>$this->createUrl('admin'),
	'Hak Akses Role'=>$this->createUrl('access',array('id'=>$model->id)),
);

$this->menu=array(
array('label'=>'List Role','url'=>array('index')),
array('label'=>'Create Role','url'=>array('create')),
array('label'=>'Update Role','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Role','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Role','url'=>array('admin')),
);
?>

<h1>Hak Akses Role <?php echo $model->nama; ?></h1>

<?php print CHtml::beginForm(); ?>

<?php $this->widget('booster.widgets.TbButton',array('buttonType'=>'submit','context'=>'primary','label'=>'Simpan','icon'=>'ok white','htmlOptions'=>array('class'=>'big-button'),)); ?>

<div>&nbsp;</div>


<table class="table table-striped table-bordered">
<thead>
<tr>
	<th>No</th>
	<th>Nama Akses</th>
	<th>Sub Akses</th>
	<th>Pilih Akses</th>
</tr>
</thead>
<?php $i=1; foreach(Access::model()->findAll(array('order'=>'nama_controller, nama_action ASC')) as $akses) { ?>
<tr>
	<td><?php print $i; ?></td>
	<td><?php print $akses->nama_controller; ?></td>
	<td><?php print $akses->nama_action; ?></td>
	<td><?php print CHtml::checkBox('RoleAccess['.$akses->id.']',$akses->cekAkses($_GET['id'])); ?></td>
</tr>
<?php $i++; } ?>
</table>

<?php print CHtml::endForm(); ?>

protected/views/role/admin.php
<?php
$this->breadcrumbs=array(
	'Data Role'=>$this->createUrl('admin'),
);

$this->menu=array(
array('label'=>'List Role','url'=>array('index')),
array('label'=>'Create Role','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('role-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>Data User Role</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah User Role',
		'icon'=>'plus',
		'context'=>'primary',
		'url'=>array('create'),
		'htmlOptions'=>array('class'=>'big-button'),
)); ?>&nbsp;

<?php $this->renderPartial('_admin',array('role'=>$role)); ?>

protected/views/role/create.php
<?php
$this->breadcrumbs=array(
	'Data Role'=>$this->createUrl('admin'),
	'Entry Role'=>$this->createUrl('create'),
);

$this->menu=array(
array('label'=>'List Role','url'=>array('index')),
array('label'=>'Manage Role','url'=>array('admin')),
);
?>

<h1>Entry Role</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/role/index.php
<?php
$this->breadcrumbs=array(
	'Roles',
);

$this->menu=array(
array('label'=>'Create Role','url'=>array('create')),
array('label'=>'Manage Role','url'=>array('admin')),
);
?>

<h1>Roles</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/role/update.php
<?php
$this->breadcrumbs=array(
	'Data Role'=>$this->createUrl('admin'),
	'Sunting Role'=>$this->createUrl('update',array('id'=>$model->id)),
);

	$this->menu=array(
	array('label'=>'List Role','url'=>array('index')),
	array('label'=>'Create Role','url'=>array('create')),
	array('label'=>'View Role','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Role','url'=>array('admin')),
	);
	?>

<h1>Update Data Role</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/role/view.php
<?php
$this->breadcrumbs=array(
	'Data Role'=>$this->createUrl('admin'),
	'Detail Role'=>$this->createUrl('view',array('id'=>$model->id)),
);

$this->menu=array(
array('label'=>'List Role','url'=>array('index')),
array('label'=>'Create Role','url'=>array('create')),
array('label'=>'Update Role','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Role','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Role','url'=>array('admin')),
);
?>

<h1>Hak Akses Role #<?php echo $model->id; ?></h1>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
		'id',
		'nama',
),
)); ?>