protected/models/Kwitansi.php
<?php

/**
 * This is the model class for table "kwitansi".
 *
 * The followings are the available columns in table 'kwitansi':
 * @property integer $id
 * @property string $nomor
 * @property integer $id_spd
 * @property integer $id_akomodasi
 * @property integer $id_refresentatif
 * @property integer $id_ssh
 * @property integer $bendahara
 * @property integer $ppk
 * @property string $bbm
 * @property string $tol
 * @property string $tiket
 * @property string $total
 *
 * The followings are the available model relations:
 * @property Akomodasi $idAkomodasi
 * @property Pejabat $bendahara0
 * @property Pejabat $ppk0
 * @property Refresentatif $idRefresentatif
 * @property Spd $idSpd
 * @property Ssh $idSsh
 */
class Kwitansi extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Kwitansi the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'kwitansi';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_spd, lama, penerima, bendahara, pptk, pa', 'numerical', 'integerOnly'=>true),
			array('nomor,spd,akomodasi,uang_harian, bendahara, pptk, pa, penerima','safe'),
			array('nomor, bbm, tol, tiket, total, akomodasi, refresentatif, uang_harian,', 'length', 'max'=>255),
			array('tanggal, program, kegiatan','safe'),
			//array('nomor','nomorUnik'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nomor, id_spd, id_akomodasi, id_refresentatif, id_ssh, bendahara, ppk, bbm, tol, tiket, total', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'penerimaRelation' => array(self::BELONGS_TO, 'Pegawai', 'penerima'),
			'akomodasi' => array(self::BELONGS_TO, 'Akomodasi', 'id_akomodasi'),
			'bendaharaRelation' => array(self::BELONGS_TO, 'Pejabat', 'bendahara'),
			'pptkRelation' => array(self::BELONGS_TO, 'Pejabat', 'pptk'),
			'paRelation' => array(self::BELONGS_TO, 'Pejabat', 'pa'),
			'refresentatif' => array(self::BELONGS_TO, 'Refresentatif', 'id_refresentatif'),
			'spd' => array(self::BELONGS_TO, 'Spd', 'id_spd'),
			'ssh' => array(self::BELONGS_TO, 'Ssh', 'id_ssh'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'tanggal' => 'Tanggal Kwitansi',
			'nomor' => 'Nomor Kwitansi',
			'id_spd' => 'Nomor SPD',
			'id_akomodasi' => 'Akomodasi',
			'id_refresentatif' => 'Representatif',
			'id_ssh' => 'Uang Harian',
			'bendahara' => 'Bendahara',
			'pptk' => 'Pejabat Pelaksana Teknis Kegiatan',
			'pa'=>'PA/KPA',
			'bbm' => 'BBM',
			'tol' => 'Tol',
			'tiket' => 'Tiket',
			'total' => 'Total',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria = Yii::app()->advancedFilters->createCriteria();
		$criteria->select = "t.*, spd.nomor_spd";
		$criteria->join = "JOIN spd ON spd.id = t.id_spd";
		$criteria->addAdvancedFilterCondition('spd.nomor_spd',$this->id_spd,true);

		$criteria->compare('id',$this->id);
		$criteria->compare('nomor',$this->nomor,true);
		//$criteria->compare('id_spd',$this->id_spd);
		$criteria->compare('penerima',$this->penerima);
		$criteria->compare('program',$this->program);
		$criteria->compare('kegiatan',$this->kegiatan);
		$criteria->compare('akomodasi',$this->akomodasi);
		$criteria->compare('refresentatif',$this->refresentatif);
		$criteria->compare('uang_harian',$this->uang_harian);
		$criteria->compare('bendahara',$this->bendahara);
		$criteria->compare('pptk',$this->pptk);
		$criteria->compare('bbm',$this->bbm,true);
		$criteria->compare('tol',$this->tol,true);
		$criteria->compare('tiket',$this->tiket,true);
		$criteria->compare('total',$this->total,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'sort'=>array(
                    'defaultOrder'=>'id DESC',
                ),
		));
	}
	
	public function nomorUnik()
	{
		$model = Kwitansi::model()->findByAttributes(array('nomor'=>$this->nomor));
		if($model!==null)
		{
			if($model->id != $this->id)
				$this->addError('nomor','Ganti nomor kwitansi, sudah ada kwitansi yang menggunakan nomor tersebut');
			
		}
	}
	
	public function getRelationField($relation,$field)
	{
		if(!empty($this->$relation->$field))
			return $this->$relation->$field;
		else
			return null;
	}
	
	public function getRelationNip($relation)
	{
		if(!empty($this->$relation))
			return $this->$relation->getNip();
		else
			return null;
	}
	
	public function getChart($type)
	{
		$list = array();
		$model = Pegawai::model()->findAll();
		
		if($type=='bar')
		{
			foreach($model as $data)
			{
				$list[] = array('type'=>'column','name'=>$data->nama,'data'=>array(
					$this->getTotal($data->id,01,date('Y')),
					$this->getTotal($data->id,02,date('Y')),
					$this->getTotal($data->id,03,date('Y')),
					$this->getTotal($data->id,04,date('Y')),
					$this->getTotal($data->id,05,date('Y')),
					$this->getTotal($data->id,06,date('Y')),
					$this->getTotal($data->id,08,date('Y')),
					$this->getTotal($data->id,07,date('Y')),
					$this->getTotal($data->id,09,date('Y')),
					$this->getTotal($data->id,10,date('Y')),
					$this->getTotal($data->id,11,date('Y')),
					$this->getTotal($data->id,12,date('Y')),
				));
			}
		}
		
		return $list;
	}
	
	public function getTotal($id,$bulan,$year)
	{
		$criteria = new CDbCriteria;
		$criteria->addCondition('MONTH(tanggal) = :month');
		$criteria->params[':month']=date($bulan);
		$criteria->addCondition('YEAR(tanggal) = :year');
		$criteria->params[':year']=date($year);
		$list = array();
		$jumlah = 0;
		
		$kwitansis = Kwitansi::model()->findAllByAttributes(array('penerima'=>$id),$criteria);
		foreach($kwitansis as $kwitansi)
		{
			$jumlah += $kwitansi->total;
		}
		$list[] = (int)$jumlah;
		
		return $list;
	}
	
	public function getUntuk()
	{
		$untuk = '';
		
		$untuk .= 'Untuk biaya perjalanan dinas ke '.$this->getRelationField('spd','tujuan');
		$untuk .= ' selama '.$this->getRelationField('spd','lama');
		$untuk .= ' ('.ucwords(trim(Bantu::getTerbilang($this->getRelationField('spd','lama'),0))).') hari';
		$untuk .= ' tgl. '.Bantu::tgl($this->getRelationField('spd','tgl_pergi'));
		$untuk .= ' s/d ';
		$untuk .= Bantu::tgl($this->getRelationField('spd','tgl_kembali'));
		$untuk .= ', dengan rincian: ';
		$untuk .= 'Uang Harian '.Bantu::rp($this->uang_harian).' x '.$this->getRelationField('spd','lama').' Hari';
		
		if(!empty($this->akomodasi))
			$untuk .= ' + Akomodasi = '.Bantu::rp($this->akomodasi);
			
		if(!empty($this->refresentatif))
			$untuk .= ' + Refresentatif = '.Bantu::rp($this->refresentatif);
			
		if(!empty($this->bbm))
			$untuk .= ' + BBM = '.Bantu::rp($this->bbm);
			
		if(!empty($this->tol))
			$untuk .= ' + Tol = '.Bantu::rp($this->tol);
			
		if(!empty($this->tiket))
			$untuk .= ' + Tol = '.Bantu::rp($this->tiket);
		
		return $untuk;
	}
}

protected/controllers/KwitansiController.php
<?php

class KwitansiController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/constellation/index';

/**
* @return array action filters
*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'accessRole'
		);
	}

	/**
	* Specifies the access control rules.
	* This method is used by the 'accessControl' filter.
	* @return array access control rules
	*/
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','delete'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('admin','create','update','cetak','cetakLengkap',
					'cetakBlanko','excel','exportExcel'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	public function actionAdmin()
	{
		$model=new Kwitansi('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Kwitansi']))
			$model->attributes=$_GET['Kwitansi'];

		$this->render('admin',array(
			'kwitansi'=>$model,
		));
	}

	/**
	* Creates a new model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	*/
	public function actionCreate()
	{
		$model=new Kwitansi;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kwitansi']))
		{
			$model->attributes=$_POST['Kwitansi'];
			
			if($model->tanggal == '0000-00-00' OR $model->tanggal == '')
				$model->tanggal = null;
			
			$model->uang_harian = str_replace('.','',$model->uang_harian);
			$model->akomodasi = str_replace('.','',$model->akomodasi);
			$model->refresentatif = str_replace('.','',$model->refresentatif);
			$model->bbm = str_replace('.','',$model->bbm);
			$model->tol = str_replace('.','',$model->tol);
			$model->tiket = str_replace('.','',$model->tiket);
			
			$model->total = 0;
			$model->total += floatval($model->uang_harian);
			$model->total += floatval($model->akomodasi);
			$model->total += floatval($model->refresentatif);
			$model->total += floatval($model->bbm);
			$model->total += floatval($model->tol);
			$model->total += floatval($model->tiket);
			
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('spd/view','id'=>$model->id_spd));
			}
		}

		$kwitansi = new Kwitansi('search');
		$kwitansi->unsetAttributes();  // clear any default values
		
		if(isset($_GET['Kwitansi']))
			$kwitansi->attributes=$_GET['Kwitansi'];

			
		$akomodasi = new Akomodasi;
		$refresentatif = new Refresentatif;
		$uangHarian = new UangHarian;
		
		$this->render('create',array(
			'model'=>$model,
			//'kwitansi'=>$kwitansi,
			//'akomodasi'=>$akomodasi,
			//'refresentatif'=>$refresentatif,
			//'uangHarian'=>$uangHarian
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kwitansi']))
		{
			$model->attributes=$_POST['Kwitansi'];
			
			if($model->tanggal == '0000-00-00' OR $model->tanggal == '')
				$model->tanggal = null;
			
			$model->uang_harian = str_replace('.','',$model->uang_harian);
			$model->akomodasi = str_replace('.','',$model->akomodasi);
			$model->refresentatif = str_replace('.','',$model->refresentatif);
			$model->bbm = str_replace('.','',$model->bbm);
			$model->tol = str_replace('.','',$model->tol);
			$model->tiket = str_replace('.','',$model->tiket);
			
			$model->total = 0;
			$model->total += floatval($model->uang_harian*$model->spd->lama);
			$model->total += floatval($model->akomodasi);
			$model->total += floatval($model->refresentatif);
			$model->total += floatval($model->bbm);
			$model->total += floatval($model->tol);
			$model->total += floatval($model->tiket);
			
			if($model->save())
			{	
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('spd/view','id'=>$model->id_spd));
			}
		}

		$kwitansi=new Kwitansi('search');
		$kwitansi->unsetAttributes();  // clear any default values
			
		if(isset($_GET['Kwitansi']))
			$kwitansi->attributes=$_GET['Kwitansi'];

		Yii::app()->user->setFlash('info','Silahkan sunting data pada kolom yang disediakan');
		
		$akomodasi = new Akomodasi;
		$refresentatif = new Refresentatif;
		$uangHarian = new UangHarian;
		
		$this->render('update',array(
			'model'=>$model,
			'kwitansi'=>$kwitansi,
			'akomodasi'=>$akomodasi,
			'refresentatif'=>$refresentatif,
			'uangHarian'=>$uangHarian
		));
	}
	
	public function actionExcel()
	{
		$this->render('excel');
	}
	
	public function actionExportExcel()
	{
		$this->layout = '//layouts/excel';
		$this->render('_excel',array('border'=>1));
	}
	
	public function actionCetakLengkap($id)
    {
	    $pdf=Yii::createComponent('application.extensions.tcpdf.ETcPdf', 'L', 'cm', 'Legal', true, 'UTF-8');
		// create new PDF document
		$pdf = new TCPDF('P', PDF_UNIT, 'Legal', true, 'UTF-8', false);
		// set document information
		$pdf->SetCreator(PDF_CREATOR);
		$pdf->SetAuthor('RINCIAN BIAYA PERJALANAN DINAS');
		$pdf->SetTitle('RINCIAN BIAYA PERJALANAN DINAS');
		$pdf->SetSubject('RINCIAN BIAYA PERJALANAN DINAS');
		$pdf->setPrintHeader(false);
		$pdf->setPrintFooter(false);
		//$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
		$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
		//$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
		
		//set auto page breaks
		$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
		// add a page
		$pdf->AddPage();
		$pdf->SetFont('times', '', 11);
		
		$model = $this->loadModel($id);
		
		
		$tanggal = Bantu::tanggal($model->tanggal);
		if($model->tanggal=='0000-00-00' OR $model->tanggal == null)
			$tanggal = '.......................';
		
		$nomor = '.......................';
		if($model->nomor!=null)
			$nomor = $model->nomor;
			
		$program = '............................................................................................';
		if($model->program!=null)
			$program = $model->program;
			
		$kegiatan = '............................................................................................';
		if($model->kegiatan!=null)
			$kegiatan = $model->kegiatan;
			
		$pa = '.............................';
		$nip_pa = '';
		if($model->pa!=null)
		{
			$pa = $model->getRelationField("paRelation","nama");
			$nip_pa = 'Nip. '.$model->getRelationField("paRelation","nip");
		}
		
		$pptk = '.............................';
		$nip_pptk = '';
		if($model->pptk!=null)
		{
			$pptk = $model->getRelationField("paRelation","nama");
			$nip_pptk = 'Nip. '.$model->getRelationField("paRelation","nip");
		}
		
		$bendahara = '.............................';
		$nip_bendahara = '';
		if($model->bendahara!=null)
		{
			$bendahara = $model->getRelationField("bendaharaRelation","nama");
			$nip_bendahara = 'Nip. '.$model->getRelationField("bendaharaRelation","nip");			
		}
		
		$nama_penerima = '';
		$jabatan_penerima = '';
		if($model->penerima!=null)
		{
			$nama_penerima = $model->getRelationField("penerimaRelation","nama");
			$jabatan_penerima = $model->getRelationField("penerimaRelation","jabatan");
		}
		
		$html = '';
		
		$html .= '<h1 style="text-align:center">PEMERINTAH KABUPATEN SERANG<br>DINASI PERHUHUNGAN, KOMUNIKAS DAN INFORMATIKA</h1>';
		
		$html .= '
			    <table width="100%">
					<tr>
						<td width="70%">&nbsp;</td>
			    		<td width="10%">Tanggal</td>
			    		<td width="20%">: '.$tanggal.'</td>
			    	</tr>
					<tr>
						<td width="70%">&nbsp;</td>
			    		<td width="10%">Nomor</td>
			    		<td width="20%">: '.$nomor.'</td>
			    	</tr>
					<tr>
						<td colspan="3" style="font-size:5">&nbsp;</td>
					</tr>
			    </table>';
			
		$html .= '<h1 style="text-align:center">TANDA BUKTI PEMBAYARAN</h1>';
		
		$html .= '<p>Sudah terima dari Bendahara Pengeluaran Kantor Dinas Perhubungan, Komunikasi dan Informatika Kabupaten Serang</p>';
		
		$html .= '	    
			    <table>
			    <tr>
					<td width="20%">Uang Sebesar</td>
					<td width="80%">: '.Bantu::rp($model->total).'</td>
				</tr>
				<tr>
					<td>Dengan huruf</td>
					<td>: '.Bantu::getTerbilang($model->total,0).'</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>: '.$model->getUntuk().'</td>
				</tr>
				<tr>
					<td>Untuk Program</td>
					<td>: '.$program.'</td>
				</tr>
				<tr>
					<td>Kegiatan</td>
					<td>: '.$kegiatan.'</td>
				</tr>
				<tr>
					<td>Kode Rekening</td>
					<td>: '.$model->getRelationField("spd","koring").'</td>
				</tr>
			    </table>';
		
		$html .= '
			<table>
			<tr>
				<td colspan="3" width="70%">&nbsp;</td>
				<td colspan="2" width="30%" style="text-align:center">Serang, '.$tanggal.'</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
				<td colspan="2" style="text-align:center">Yang Menerima</td>
			</tr>
			<tr>
				<td style="text-align:center">Pengguna Anggaran/</td>
				<td style="text-align:center">PPTK</td>
				<td style="text-align:center">Bendahara Pengeluaran</td>
				<td>Nama</td>
				<td style="font-size:8">: '.$nama_penerima.'</td>
			</tr>
			<tr>
				<td style="text-align:center">Kuasa Pengguna Anggaran</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>Pangkat Jabatan</td>
				<td style="font-size:8">: '.$jabatan_penerima.'</td>
			</tr>

protected/views/kwitansi/_admin.php
<?php $this->widget('booster.widgets.TbGridView',array(
		'id'=>'kwitansi-grid',
		'type'=>'striped bordered',
		'dataProvider'=>$kwitansi->search(),
		'filter'=>$kwitansi,
		'columns'=>array(
			array(
				'class'=>'CDataColumn',
				'name'=>'nomor',
				'header'=>'Nomor',
				'type'=>'raw',
				'value'=>'$data->nomor',
			),
			
			array(
				'class'=>'CDataColumn',
				'name'=>'id_spd',
				'header'=>'No. SPD',
				//'type'=>'raw',
				'value'=>'$data->getRelationField("spd","nomor_spd")',
				//'filter'=>CHtml::listData(Spd::model()->findAll(),'id','nomor_spd')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'tanggal',
				'header'=>'Tanggal Kwitansi',
				'type'=>'raw',
				'value'=>'Yii::app()->dateFormatter->format("dd-MM-yyyy",$data->tanggal)',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'penerima',
				'header'=>'Penerima',
				'type'=>'raw',
				'value'=>'$data->getRelationField("penerimaRelation","nama")',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'total',
				'header'=>'Total',
				'type'=>'raw',
				'value'=>'number_format($data->total, 0,",",".")',
			),
			
			array(
				'class'=>'booster.widgets.TbButtonColumn',
			)
			
		),
)); ?>

protected/views/kwitansi/admin.php
<?php
$this->breadcrumbs=array(
	'Data Kwitansi'=>$this->createUrl('admin'),
);

$this->menu=array(
array('label'=>'List Kwitansi','url'=>array('index')),
array('label'=>'Manage Kwitansi','url'=>array('admin')),
);
?>

<h1>Data Tanda Bukti Pembayaran</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah Kwitansi',
		'icon'=>'plus',
		'context'=>'primary',
		'url'=>array('create'),
		'htmlOptions'=>array('class'=>'big-button'),
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Setting Posisi Cetak Kwitansi',
		'icon'=>'wrench',
		'context'=>'primary',
		'url'=>array('posisiCetak/setting','jenis_surat'=>'2'),
		'htmlOptions'=>array('class'=>'big-button'),
)); ?>&nbsp;

<div style="overflow:auto">
	<?php echo $this->renderPartial('_admin',array('kwitansi'=>$kwitansi)); ?>
</div>

protected/views/kwitansi/create.php
<?php
$this->breadcrumbs=array(
	'Data Kwitansi'=>$this->createUrl('admin'),
	'Input Kwitansi'=>$this->createUrl('create'),
);

$this->menu=array(
array('label'=>'List Kwitansi','url'=>array('index')),
array('label'=>'Manage Kwitansi','url'=>array('admin')),
);
?>

<h1>Tanda Bukti Pembayaran</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
	

protected/views/kwitansi/view.php
<?php $this->breadcrumbs=array(
	'Data Kwitansi'=>$this->createUrl('admin'),
	'Detail Kwitansi'=>$this->createUrl('update',array('id'=>$model->id)),
); ?>
<h1>Detail Kwitansi</h1>
<?php $this->widget('booster.widgets.TbButton',array(
		'label' => 'Lihat SPD',
		'buttonType'=>'link',
		'icon'=>'arrow-left',
		'context' => 'primary',
		'url'=>array('spd/view','id'=>$model->id_spd),
		'htmlOptions'=>array('class'=>'big-button')
)); ?>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'context'=>'primary',
		'label'=>'Sunting',
		'icon'=>'pencil',
		'url'=>array('kwitansi/update','id'=>$model->id),
		'htmlOptions'=>array('class'=>'big-button')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'context'=>'primary',
		'label'=>'Kelola',
		'icon'=>'list',
		'url'=>array('kwitansi/admin'),
		'htmlOptions'=>array('class'=>'big-button')
)); ?>
<?php $this->widget('booster.widgets.TbButtonGroup',array(
        'context' => 'primary',
        'buttons' => array(
            array(
                'label' => 'Cetak Kwitansi',
				'icon' => 'print',
				'htmlOptions'=>array('class'=>'big-button'),
                'items' => array(
					array('label' => 'Cetak Blanko', 'url' => array('kwitansi/cetakBlanko','id'=>$model->id),'linkOptions'=>array('target'=>'_blank')),
					array('label' => 'Cetak Lengkap', 'url' => array('kwitansi/cetakLengkap','id'=>$model->id),'linkOptions'=>array('target'=>'_blank')),
					'---',
                    array('label' => 'Setting Posisi Kwitansi', 'url' => array('posisiCetak/setting','jenis_surat'=>'2')),
				)
            ),
        ),
)); ?>


<div>&nbsp;</div>

<div class="">	
	<?php $this->widget('booster.widgets.TbDetailView',array(
		'data'=>$model,
		'type'=>'striped bordered',
		'attributes'=>array(
			'nomor',
			array(
				'label'=>'Tanggal Kwitansi',
				'value'=>Bantu::tanggal($model->tanggal)
			),
			array(
				'label'=>'Nomor SPD',
				'type'=>'raw',
				'value'=>CHtml::encode($model->getRelationField("spd","nomor_spd"))
			),
			'program',
			'kegiatan',
			array(
				'label'=>'Akomodasi',
				'type'=>'raw',
				'value'=>'Rp '.number_format($model->akomodasi, 2,",",".")
			),
			array(
				'label'=>'Refresentatif',
				'type'=>'raw',
				'value'=>'Rp '.number_format($model->refresentatif, 2,",",".")
			),
			array(
				'label'=>'Uang Harian',
				'type'=>'raw',
				'value'=>'Rp '.number_format($model->uang_harian, 2,",",".")
			),
			array(
				'label'=>'Bendahara',
				'type'=>'raw',
				'value'=>$model->getRelationField("bendaharaRelation","nama")
			),
			array(
				'label'=>'PPTK',
				'type'=>'raw',
				'value'=>$model->getRelationField("pptkRelation","nama")
			),
			array(
				'label'=>'PA/KPA',
				'type'=>'raw',
				'value'=>$model->getRelationField("paRelation","nama")
			),
			array(
				'label'=>'BBM',
				'type'=>'raw',
				'value'=>'Rp '.number_format($model->bbm, 2,",",".")
			),
			array(
				'label'=>'Tol',
				'type'=>'raw',
				'value'=>'Rp '.number_format($model->tol, 2,",",".")
			),
			array(
				'label'=>'Tiket',
				'type'=>'raw',
				'value'=>'Rp '.number_format($model->tiket, 2,",",".")
			),
			array(
				'label'=>'Total',
				'type'=>'raw',
				'value'=>'Rp <b>'.number_format($model->total, 2,",",".").'</b>'
			),
		),
)); ?>
</div>